### ISSUE TITLE
mime.replace is not a function

### ISSUE THREAD

**Issue by Zecradox** [RyanAfrish7/thumbsupply#2]
When using the following code:

`
thumbsupply.generateThumbnail(filepath)
`

I get the error

`
mime.replace is not a function
`

**edit: the file is named about 10 different numbers (with no file extension)**

**Comment by RyanAfrish7** [comment]
Thanks for pointing out. This issue is fixed in e29a11bfa1323dbbfdfb829feefb37996bfd4f97 and a patch `0.3.1` is released.
