### ISSUE TITLE
Make cacheDir configurable

### ISSUE THREAD

**Issue by kj800x** [RyanAfrish7/thumbsupply#3]
It would be great if it were possible to configure the `cacheDir` that `thumbsupply` uses. The default `~/.cache/thumbsupply` is good in most cases, but it would be great for me to be able to have the data on my hard drive partition where the rest of my application is stored from instead of in my home directory.

**Comment by RyanAfrish7** [comment]
Made cacheDir configurable with commit https://github.com/RyanAfrish7/thumbsupply/commit/bffe41c8828193fb06d05a1c48bb0de7c9d5f133

Please checkout v0.4.0.
